version: 2
sources:
    - name: snowflake_data
      database: "{{('SALES')}}"
      schema: RAWDWATA
      tables:
        - name: RAW_LINEITEM
          columns:
            - name: l_orderkey
              tests:
                - not_null
            - name: l_quantity
              tests:
                - not_null
            - name: l_linenumber
              tests:
                - not_null  
        - name: RAW_NATION
          columns:
            - name: n_nationkey
              tests:
                - unique
                - not_null
            - name: n_name
              tests:
                - not_null
        - name: RAW_ORDER
          columns:
            - name: o_orderkey
              tests:
               - unique
               - not_null

        - name: RAW_CUSTOMER 

